name: Test Python Labs

on:
  push:
    branches:
      - 'main'
      - 'lab-*'
    paths:
      - 'labs/**'  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Step 4: Show modified files for debugging
    - name: Show Modified Files
      run: |
        echo "Changed files in the last commit:"
        git diff --name-only HEAD~1 HEAD

    # Step 5: Run tests
    - name: Run Tests
      run: |
        # Get modified lab directories
        MODIFIED_LABS=$(git diff --name-only HEAD~1 HEAD | grep '^labs/lab_' | cut -d'/' -f1-2 | sort -u)
        
        if [ -z "$MODIFIED_LABS" ]; then
          echo "No lab directories were modified. Skipping tests."
          exit 0
        fi
        
        echo "Modified lab directories:"
        echo "$MODIFIED_LABS"
        
        # Run tests only for modified labs
        for lab in $MODIFIED_LABS; do
          echo "Running tests for $lab..."
          cd $lab
          python -m pytest tests/ -v
          cd ../..
        done
