name: Test Python Labs

on:
  push:
    branches:
      - 'main'
      - 'lab-*'
    paths:
      - 'labs/**'  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Step 4: Show modified files for debugging
    - name: Show Modified Files
      run: |
        echo "Changed files in the last commit:"
        git diff --name-only HEAD~1 HEAD

    # Step 5: Find and test modified labs
    - name: Run Tests in Modified Labs
      run: |
        # Extract lab directories that were modified (like labs/lab_01)
        MODIFIED_LABS=$(git diff --name-only HEAD~1 HEAD | grep '^labs/lab_' | cut -d'/' -f1-2 | sort -u)

        if [ -z "$MODIFIED_LABS" ]; then
          echo "No lab directories were modified. Skipping tests."
          exit 0
        fi

        echo "Modified lab directories:"
        echo "$MODIFIED_LABS"

        # Loop over each modified lab directory and run tests
        for LAB in $MODIFIED_LABS; do
          echo "----------------------------------------"
          echo "Running tests for $LAB..."
          if [ -d "$LAB/tests" ]; then
            cd $LAB
            python -m pytest tests/ -v || exit 1
            cd ../..
          else
            echo "No 'tests' directory found in $LAB. Skipping."
          fi
        done
