name: Test Python Labs

on:
  push:
    branches:
      - main
      - 'lab-*'  # Matches any branch starting with lab-
  pull_request:
    branches:
      - main
    paths:
      - 'labs/**'  # Trigger on changes to any lab files

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Detect modified labs
      id: detect-labs
      run: |
        # Get list of modified lab directories
        MODIFIED_LABS=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '^labs/' | cut -d'/' -f1-2 | sort -u)
        echo "Modified labs: $MODIFIED_LABS"
        echo "labs=${MODIFIED_LABS}" >> $GITHUB_OUTPUT
    
    - name: Run tests for modified labs
      run: |
        # Read the labs from the previous step
        LABS=$(echo "${{ steps.detect-labs.outputs.labs }}" | tr ' ' '\n')
        
        for lab in $LABS; do
          if [ -d "$lab/tests" ]; then
            echo "Running tests for $lab..."
            cd $lab
            python -m pytest tests/ -v
            cd ../..
          else
            echo "No tests directory found in $lab, skipping tests."
          fi
        done
    
    - name: Check exercise implementations
      run: |
        # Read the labs from the previous step
        LABS=$(echo "${{ steps.detect-labs.outputs.labs }}" | tr ' ' '\n')
        
        for lab in $LABS; do
          if [ -d "$lab/exercises" ]; then
            echo "Checking exercise implementations in $lab..."
            cd $lab
            
            # Run each exercise file
            for exercise in exercises/*.py; do
              if [ -f "$exercise" ]; then
                echo "Running $exercise..."
                python "$exercise"
              fi
            done
            
            cd ../..
          else
            echo "No exercises directory found in $lab, skipping implementation checks."
          fi
        done 